"""schema_v1_domain_models_and_razorpay

Revision ID: 7c97326e1d67
Revises:
Create Date: 2026-08-23 14:35:47.145568

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c97326e1d67"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_payment_failures_razorpay_payment_id"),
        "payment_failures",
        ["razorpay_payment_id"],
        unique=False,
    )
    op.drop_column("recovery_actions", "precedent_sample_size")
    op.drop_column("recovery_actions", "empirical_confidence")
    op.drop_column("recovery_actions", "llm_stated_confidence")
    op.drop_column("recovery_cases", "playbook_precedents_json")
    op.drop_column("recovery_cases", "precedent_count")
    op.drop_column("recovery_cases", "empirical_confidence")
    op.create_index(
        op.f("ix_transactions_razorpay_order_id"),
        "transactions",
        ["razorpay_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_razorpay_order_id"), table_name="transactions")
    op.add_column(
        "recovery_cases",
        sa.Column(
            "empirical_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "recovery_cases",
        sa.Column("precedent_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "recovery_cases",
        sa.Column("playbook_precedents_json", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "recovery_actions",
        sa.Column(
            "llm_stated_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "recovery_actions",
        sa.Column(
            "empirical_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "recovery_actions",
        sa.Column("precedent_sample_size", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_payment_failures_razorpay_payment_id"), table_name="payment_failures")
    # ### end Alembic commands ###
