# Deterministic Policy Bounds & Limits
MAX_RETRY_ATTEMPTS = 3
MAX_DISCOUNT_PERCENT = 10.0
HIGH_VALUE_THRESHOLD_INR = 25000.0
MAX_PROMISE_FOLLOWUPS = 1
MIN_PRECEDENT_SAMPLE_SIZE = 3

# Execution Simulators Cost Structure (INR)
COST_WHATSAPP_INR = 0.50
COST_EMAIL_INR = 0.10
COST_PAYMENT_LINK_INR = 0.00
COST_RETRY_INR = 0.00
