from enum import Enum


class CommunicationChannel(str, Enum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH = "PUSH"


class PaymentMethod(str, Enum):
    UPI = "UPI"
    CARD = "CARD"
    NETBANKING = "NETBANKING"
    WALLET = "WALLET"
    AUTODEBIT = "AUTODEBIT"


class TransactionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    REFUNDED = "REFUNDED"


class FailureReason(str, Enum):
    BANK_DECLINED = "BANK_DECLINED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    NETWORK_ERROR = "NETWORK_ERROR"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    USER_DROPOFF = "USER_DROPOFF"
    EXPIRED_CARD = "EXPIRED_CARD"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    SYSTEM_FAULT = "SYSTEM_FAULT"


class LeakType(str, Enum):
    TRANSACTION_FAILURE = "TRANSACTION_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_CANCEL_INTENT = "SUBSCRIPTION_CANCEL_INTENT"
    PROMISE_BREACH = "PROMISE_BREACH"


class CaseStatus(str, Enum):
    DETECTED = "DETECTED"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    BLOCKED = "BLOCKED"


class ActionType(str, Enum):
    RETRY_PAYMENT = "RETRY_PAYMENT"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    SEND_WHATSAPP = "SEND_WHATSAPP"
    SEND_EMAIL = "SEND_EMAIL"
    OFFER_INCENTIVE = "OFFER_INCENTIVE"
    ESCALATE_HUMAN = "ESCALATE_HUMAN"


class ActionOutcome(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    IGNORED = "IGNORED"


class PolicyDecision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"


class PromiseStatus(str, Enum):
    PENDING = "PENDING"
    KEPT = "KEPT"
    BROKEN = "BROKEN"


class StrategyType(str, Enum):
    BASELINE_RETRY_ONCE = "BASELINE_RETRY_ONCE"
    AI_ORCHESTRATOR = "AI_ORCHESTRATOR"
