export const AGENT_ACTIVITY_CONSTANTS = {
  PAGE_TITLE: 'Agent Activity',
  PAGE_SUBTITLE: 'Monitor live agent operations and activity across all recovery cases',

  STATS: {
    ACTIVE_AGENTS: 'Active Agents',
    ACTIVE_CASES: 'Active Cases',
    ACTIONS_TODAY: 'Actions Today',
    SUCCESS_RATE: 'Success Rate',
    AVG_TIME: 'Avg Processing Time',
    RAG_PLAYBOOK_STORE: 'RAG Playbook Store',
    CASES_LABEL: 'cases',
    ALL_AGENTS_ONLINE: 'All Agents Online',
    EMPIRICAL_ACCURACY: '↑ Empirical Accuracy',
    AUTONOMOUS_DECISIONS: 'Autonomous Decisions',
    IN_ACTIVE_RECOVERY: 'In Active Recovery',
    PERSISTENT_MEMORY_ACTIVE: 'Persistent Memory Active',
  },

  PLAYBOOK_DRAWER: {
    TITLE: 'RAG Knowledge Store',
    SUBTITLE: 'Long-term episodic memory & precedent intelligence in ChromaDB',
    BADGE_LABEL: 'ChromaDB Persistent Store',
    SECTION_OVERVIEW: 'Memory Overview',
    TOTAL_STORED_LABEL: 'Total Stored Precedents',
    BASELINE_LABEL: 'Baseline Precedents',
    LEARNED_LABEL: 'Dynamically Learned',
    SECTION_FAILURES: '1. Failure Category Breakdown',
    FAILURE_REASON_COL: 'Failure Reason',
    PRECEDENT_CASES_COL: 'Stored Precedent Cases',
    TOTAL_LABEL: 'Total',
    SECTION_OUTCOMES: '2. Learned Outcomes & Actions',
    OUTCOMES_RECORDED: 'Outcomes Recorded:',
    RECOVERED_LABEL: 'Recovered / Succeeded',
    FAILED_LABEL: 'Failed / Escalated / Blocked',
    ACTIONS_ANALYZED: 'Action Types Analyzed:',
    EMPTY_BREAKDOWN: 'No breakdown data available in knowledge store.',
    CLICK_TO_INSPECT: 'Click to inspect memory breakdown',
  },

  SIDEBAR_TITLE: 'Specialized Agents',
  ALL_AGENTS: 'All Agents',
  FEED_TITLE: 'Live Activity Stream',
  EVENTS_RECORDED: 'events recorded',
  DECISION_LABEL: 'Decision:',
  EMPIRICAL_CONFIDENCE_LABEL: 'Empirical Confidence:',
  PRECEDENTS_LABEL: 'Precedents:',
  LATENCY_LABEL: 'latency',
  PROCESSED_FALLBACK: 'PROCESSED',
  STATUS_PLACEHOLDER: 'Status',
  TIME_RANGE_PLACEHOLDER: 'Time Range',
  RESET_BUTTON: 'Reset',

  STATUS_OPTIONS: [
    { value: 'all', label: 'All Statuses' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Approved', label: 'Approved' },
    { value: 'Escalated', label: 'Escalated' },
  ],

  TIME_RANGE_OPTIONS: [
    { value: '24h', label: 'Last 24 hours' },
    { value: '7d', label: 'Last 7 days' },
    { value: '30d', label: 'Last 30 days' },
    { value: 'all', label: 'All time' },
  ],

  SEARCH_PLACEHOLDER: 'Filter activities by case ID, agent, action...',
  EMPTY_STATE: 'No agent activity logs match the selected filters.',
} as const;
